import "./global.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}

// import "./global.css";
// // import Footer from "@/components/Footer";
// // import Navbar from "@/components/Navbar";

// export const metadata = {
//   title: "Flexibble",
//   description: "Showcase and discover remarkable developer projects",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         {/* <Navbar /> */}
//         <main>{children}</main>
//         {/* <Footer /> */}
//       </body>
//     </html>
//   );
// }
